config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'users#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes
    end
  end
  
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, format: :json do 
          resources :comments, format: :json 
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :manage, Comment, author_id: user.id
    can :manage, Post, author_id: user.id
    can :read, :all
    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_save :update_comments_count

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  def update_comments_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  after_save :update_likes_count

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_likes_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_posts_count

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id', dependent: :destroy
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def update_posts_count
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.includes(:author).limit(5).order(created_at: :asc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id'
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.limit(3).order(created_at: :asc)
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  load_and_authorize_resource

  def index
    comments = Comment.where(author_id: params[:user_id])
    render json: comments, status: :ok
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], user_id: current_user.id, post_id: @post.id)
    if @comment.save
      render json: @comment
    else
      render error: { error: 'Unable to create comments' }, status: 400
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    posts = Post.where(author_id: params[:user_id])
    render json: posts, status: :ok
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    users = User.all
    render json: users, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    @post = Post.find(params[:post_id])

    if @comment.save
      redirect_to user_posts_path(@post.author_id)
    else
      render :new, alert: 'ERROR! something went wrong while creating the comment'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.post.decrement!(:comments_counter)
    @comment.destroy!
    flash[:success] = 'The comment was successfully deleted.'
    redirect_to user_posts_path(current_user)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(post_id: @post.id, author_id: current_user.id)
    if @like.save
      redirect_to user_posts_path(id: @post.author_id)
    else
      redirect_to @post
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource param_method: :posts_params

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    @post.author = current_user
    if @post.save
      redirect_to user_posts_path(id: @post.author_id)
    else
      render :new, alert: 'ERROR! something went wrong while creating the post'
    end
  end

  def show
    @post = Post.includes(:author).find(params[:id])
    @user = current_user
  end

  def destroy
    @post = Post.find(params[:id])
    @post.author.decrement!(:posts_counter)
    @post.destroy
    flash[:success] = 'Post was successfully deleted'
    redirect_to user_path(@post.author)
  end

  private

  def posts_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment, url: user_post_comments_path, class: "add-comment" do |form| %>
  <%= form.label :Add_a_comment  %>
  <%= form.text_area :text %>
  <%= form.submit class: "btn" %>
<%end%>

app/views/confirmables/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap" rel="stylesheet">
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <footer class="footer">Abel Gebeyehu &copy 2022</footer>
  </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>

  <body>
    <div class="root-container posts-comments-container">
      <div class="back-link-container">
        <%= link_to "Home > ", authenticated_root_path, class: "navigational-link" %>
        <%= link_to "Back", :back, class: "back-link" %>
      </div>
      <%= render 'shared/user_info', user: @user %>
      <div class="posts-comments">
        <% @posts.each_with_index do |post, post_no| %>
          <div class="post-comments">
              <%= render 'shared/post_info', post: post, post_no: post_no, user: @user %>
            <div class="comments">
              <% post.recent_comments.each do |comment| %>
                <%= render 'shared/comment', comment: comment, user: @user, post: post %>
              <% end %>
              <button class="btn add-comment-btn"><%= link_to 'Add comment', new_user_post_comment_path(@user, post) %></button>
            </div>
          </div>
        <% end %>
        <button class="btn">Pagination</button>
      </div>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path, class: "add-post" do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :Write_your_post %>
  <%= form.text_area :text%>
  <%= form.submit "Create post", disable_with: 'Submiting...', class: "btn" %>
<% end %>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>

  <body>
    <div class="root-container post-detail-container">
      <div class="back-link-container">
        <%= link_to "Home > ", authenticated_root_path, class: "navigational-link" %>
        <%= link_to "Back", :back, class: "back-link" %>
      </div>
      <div class="post-header">
        <div class="user-name"><%= @post.title %> by: <%=@post.author.name%></div>
        <div class="comments-likes">Comments: <%=@post.comments_counter%>, Likes: <%=@post.likes_counter%></div>
      </div>
      <div class="post-detail">
        <%=@post.text%>
      </div>
      <div class="comments">
        <% @post.recent_comments.each do |comment| %>
          <%= render 'shared/comment', comment: comment, post: @post, user: @user %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_comment.html.erb
<div class="comment">
  <span class="user-name"><%=comment.author.name%>: <%=comment.text%></span>
  <% if can? :destroy, comment %>
    <%= form_with model: comment, url: user_post_comment_path(user, post, id: comment.id), method: :delete do |f| %>
        <%= f.submit "X", class: 'remove-btn' %>
    <% end %>
  <% end %>
</div>

app/views/shared/_post_info.html.erb
<%= link_to user_post_path(user, post) do %>
  <div class="post">
      <div class="back-link-container">
        <%= link_to "Home > ", authenticated_root_path, class: "navigational-link" %>
        <%= link_to "Back", :back, class: "back-link" %>
      </div>
    <div class="post-heading">
      <div class="content">
        <h3><%= post.title %></h3>
        <p> <%= post.text.truncate_words(5) %> </p>
      </div>
      <div class="delete-post">
        <% if can? :destroy, post%>
          <%= form_with model: post, url: user_post_path(user, post), method: :delete do |f| %>
            <%= f.submit "DELETE", class: 'delete-post-btn' %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="comments-likes">
      <div class="like-comment-btn">
        <%= form_with model: @like, url: user_post_likes_path(post_id: post.id, user_id: user.id) do |form| %>
          <%= form.submit "Like", class: "btn like-btn" %>
        <% end %>
      </div>
      <div class="content">
        Comments: <span class="comments-value"> <%= post.comments_counter %></span>, Likes: <span class="likes-value"> <%= post.likes_counter %> </span>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user">
  <div class="user-img">
    <img src=<%= user.photo %> alt="User-image">
  </div>
  <div class="user-posts">
    <h1><%= user.name %></h1>
    <p class="posts-amount">Number of posts: <span class="posts-value"><%= user.posts_counter %></span> </p>
  </div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>

  <body>
    <div class="root-container users">
    <div class="profile-customize-btns">
      <% unless user_signed_in? %>
        <%= button_to "Login", new_user_session_path, class: "login-btn" %>
      <% else %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "logout-btn" %>
      <% end %>
      <%= button_to "Edit Profile", edit_user_registration_path, method: 'get', class: "logout-btn"%>
    </div>
  
      <% @users.each do |user| %>
        <%= link_to(user) do %>
          <%= render "shared/user_info", user: user %>
        <%end%>
      <%end%>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>

  <body>
    <div class="root-container user-container">
      <div class="back-link-container">
        <%= link_to "Home > ", authenticated_root_path, class: "navigational-link" %>
        <%= link_to "Back", :back, class: "back-link" %>
      </div>
      <%= render 'shared/user_info', user: @user %>
      <div class="bio-container">
        <h3>Bio</h3>
        <p class="bio"> <%=@user.bio%> </p>
      </div>
      <div class="posts">
        <% @user.recent_posts.each_with_index do |post, post_no| %>
          <%= render 'shared/post_info', post: post, post_no: post_no, user: @user %>
        <%end%>
        <button class="btn"> <%= link_to 'See all posts', user_posts_path(@user)%> </button>
        <button class="btn"> <%= link_to 'Add a post', new_user_post_path(@user)%> </button>
      </div>
    </div>
  </body>
</html>